<?php

use Illuminate\Database\Seeder;
use App\Ficha;

class FichaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /*
        Ficha::create([
            'Nombres' => 'Rosa Maria de Jesus',
            'Apellidos' => 'Almeida Naranjo',   
            'CedulaRuc' => '0500109897',   
            'DireccionDomicilio' => 'Pichincha 37-46 y Roosvel',   
            'TelefonoDomicilio' => '2813521',   
            'DireccionCobro' => 'Quito',   
            'TelefonoCobro' => '0983358394',   
            'Referencia' => 'Casa de un piso color verde',
            'Latitud' => '-0.8386899',
            'Longitud' => '-78.6664006',
            'CobroDomicilio' => 0,    
            'Archivada' => 1,
            'FechaInscripcion' => '2020/05/05',
            'Email' => 'rosaa@gmail.com',
            'ValorInscripcion' => 50,
            'ValorMaterial' => 5,
            'ValorOtros' => 10,
            'ValorMensual' => 22,    
            'FechaCobro' => '2020/05/05',
            'Observacion' => '$faker->text($maxNbChars = 50)',
            'Estado' => 0,
            'TvAdicional' => 2,
            'Filtro' => 1,
            'MensualidadesPendientes' => 2,
            'Factura' => 1,    
            'Renegociar' => 0,
            'PagadoHasta' => '2020/05/05',
            'NumSerieEquipo' => 'Str::random(10)',
            'EquipoRetirado' => 1,
            'IdZona' => 1,
            'IdServicio' => 4,
            'IdUsuario' => 8,
            ]);
        Ficha::create([
            'Nombres' => 'Ramiro Leonardo',
            'Apellidos' => 'Razo Tapia',   
            'CedulaRuc' => '0500141726',   
            'DireccionDomicilio' => 'Felix Valencia',   
            'TelefonoDomicilio' => '2810543',   
            'DireccionCobro' => 'Cuenca',   
            'TelefonoCobro' => '0989808394',   
            'Referencia' => 'Lado derecho de hotel Makroz y Quito',
            'Latitud' => '-0.9340311',
            'Longitud' => '-78.6145758',
            'CobroDomicilio' => 0,    
            'Archivada' => 1,
            'FechaInscripcion' => '2020/05/05',
            'Email' => 'ramiror@gmail.com',
            'ValorInscripcion' => 50,
            'ValorMaterial' => 5,
            'ValorOtros' => 10,
            'ValorMensual' => 29,    
            'FechaCobro' => '2020/05/05',
            'Observacion' => '$faker->text($maxNbChars = 50)',
            'Estado' => 1,
            'TvAdicional' => 2,
            'Filtro' => 1,
            'MensualidadesPendientes' => 2,
            'Factura' => 1,    
            'Renegociar' => 0,
            'PagadoHasta' => '2020/05/05',
            'NumSerieEquipo' => 'Str::random(10)',
            'EquipoRetirado' => 1,
            'IdZona' => 3,
            'IdServicio' => 3,
            'IdUsuario' => 9,
            ]);
             Ficha::create([
                                'Nombres' => 'Manuel Julio',
                                'Apellidos' => 'Otañez Salazar',   
                                'CedulaRuc' => '0101020782',   
                                'DireccionDomicilio' => 'Alaquez 3-35 y Pumacunchi',   
                                'TelefonoDomicilio' => '0984023937',   
                                'DireccionCobro' => 'Cuenca',   
                                'TelefonoCobro' => '0989808394',   
                                'Referencia' => 'Taller de costura viñeta',
                                'Latitud' => '-0.9340311',
                                'Longitud' => '-78.6145758',
                                'CobroDomicilio' => 0,    
                                'Archivada' => 1,
                                'FechaInscripcion' => '2020/05/05',
                                'Email' => 'manuelo@gmail.com',
                                'ValorInscripcion' => 50,
                                'ValorMaterial' => 5,
                                'ValorOtros' => 10,
                                'ValorMensual' => 29,    
                                'FechaCobro' => '2020/05/05',
                                'Observacion' => '$faker->text($maxNbChars = 50)',
                                'Estado' => 1,
                                'TvAdicional' => 2,
                                'Filtro' => 1,
                                'MensualidadesPendientes' => 2,
                                'Factura' => 1,    
                                'Renegociar' => 0,
                                'PagadoHasta' => '2020/05/05',
                                'NumSerieEquipo' => 'Str::random(10)',
                                'EquipoRetirado' => 1,
                                'IdZona' => 3,
                                'IdServicio' => 3,
                                'IdUsuario' => 10,
                                ]);
                Ficha::create([
                    'Nombres' => 'Francisco Anibal',
                    'Apellidos' => 'Viteri Carrillo',   
                    'CedulaRuc' => '0500158241',   
                    'DireccionDomicilio' => 'Juan Abel Echeverría 12-86 y Oriente',   
                    'Referencia' => 'Quinta casa al occidente',
                    'TelefonoDomicilio' => '2811851', 
                    'Email' => 'franciscov@gmail.com',  
                    'IdUsuario' => 11,
                    'DireccionCobro' => 'Cuenca',   
                    'TelefonoCobro' => '0989808394',   
                    'Latitud' => '-0.9340311',
                    'Longitud' => '-78.6145758',
                    'CobroDomicilio' => 0,    
                    'Archivada' => 1,
                    'FechaInscripcion' => '2020/05/05',
                    'ValorInscripcion' => 50,
                    'ValorMaterial' => 5,
                    'ValorOtros' => 10,
                    'ValorMensual' => 29,    
                    'FechaCobro' => '2020/05/05',
                    'Observacion' => '$faker->text($maxNbChars = 50)',
                    'Estado' => 1,
                    'TvAdicional' => 2,
                    'Filtro' => 1,
                    'MensualidadesPendientes' => 2,
                    'Factura' => 1,    
                    'Renegociar' => 0,
                    'PagadoHasta' => '2020/05/05',
                    'NumSerieEquipo' => 'Str::random(10)',
                    'EquipoRetirado' => 1,
                    'IdZona' => 3,
                    'IdServicio' => 3,
                    ]);

Ficha::create([
    'Nombres' => 'Segundo Enrique',
    'Apellidos' => 'Iza Hidalgo',   
    'CedulaRuc' => '0500171830',   
    'DireccionDomicilio' => 'Ciudadela el Mag calle el copal y rafael cajiao',   
    'Referencia' => 'Casa de un piso',
    'TelefonoDomicilio' => '0987285481', 
    'Email' => 'segundoi@gmail.com',  
    'IdUsuario' => 12,
    'DireccionCobro' => 'Cuenca',   
    'TelefonoCobro' => '0989808394',   
    'Latitud' => '-0.9340311',
    'Longitud' => '-78.6145758',
    'CobroDomicilio' => 0,    
    'Archivada' => 1,
    'FechaInscripcion' => '2020/05/05',
    'ValorInscripcion' => 50,
    'ValorMaterial' => 5,
    'ValorOtros' => 10,
    'ValorMensual' => 29,    
    'FechaCobro' => '2020/05/05',
    'Observacion' => '$faker->text($maxNbChars = 50)',
    'Estado' => 1,
    'TvAdicional' => 2,
    'Filtro' => 1,
    'MensualidadesPendientes' => 2,
    'Factura' => 1,    
    'Renegociar' => 0,
    'PagadoHasta' => '2020/05/05',
    'NumSerieEquipo' => 'Str::random(10)',
    'EquipoRetirado' => 1,
    'IdZona' => 3,
    'IdServicio' => 3,
    ]);
    Ficha::create([
        'Nombres' => 'Luis Alberto',
        'Apellidos' => 'Paucar Romero',   
        'CedulaRuc' => '0300936713',   
        'DireccionDomicilio' => 'Saquisilí 2-65 y Tanicuchi',   
        'Referencia' => 'Viñeta:0005418',
        'TelefonoDomicilio' => '2803326', 
        'Email' => 'luisp@gmail.com',  
        'IdUsuario' => 13,
        'DireccionCobro' => 'Cuenca',   
        'TelefonoCobro' => '0989808394',   
        'Latitud' => '-0.9340311',
        'Longitud' => '-78.6145758',
        'CobroDomicilio' => 0,    
        'Archivada' => 1,
        'FechaInscripcion' => '2020/05/05',
        'ValorInscripcion' => 50,
        'ValorMaterial' => 5,
        'ValorOtros' => 10,
        'ValorMensual' => 29,    
        'FechaCobro' => '2020/05/05',
        'Observacion' => '$faker->text($maxNbChars = 50)',
        'Estado' => 1,
        'TvAdicional' => 2,
        'Filtro' => 1,
        'MensualidadesPendientes' => 2,
        'Factura' => 1,    
        'Renegociar' => 0,
        'PagadoHasta' => '2020/05/05',
        'NumSerieEquipo' => 'Str::random(10)',
        'EquipoRetirado' => 1,
        'IdZona' => 3,
        'IdServicio' => 3,
        ]);

     */      
    }
}
